### ISSUE TITLE
Glitchy channel when sending messages

### ISSUE THREAD

**Issue by LarveyOfficial** [AlexisJonsson/AlexisJonsson.github.io#10]
When sending a message It causes the channel to get glitchy and do this weird rubber banding effect. It seems its loading the entire user message then combining it into 1.

Examples:

[With the theme on](https://cdn.larvey.gg/krfl5aucz9a)

[Without the theme on](https://larvey.loves-ani.me/krfl5zfxt9a)

**Comment by AlexisJonsson** [comment]
This should be resolved with my latest update now.

**Comment by LarveyOfficial** [comment]
https://larvey.sucks-at.life/krjc203wc9a

It seems the glitch still happens on the newest update.
